# Pandas 한번에 제대로 배우기




---



In [1]:
import pandas as pd
import numpy as np

pd.__version__

'1.2.4'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0,0.25,0.5,0.75,1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [4]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s[1]

0.25

In [6]:
#슬라이싱 
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [10]:
# 인덱스 지정
s = pd.Series([0,0.25,0.5,0.75,1.0],
             index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [11]:
'b' in s

True

In [12]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
             index=[2,4,6,8,10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
# 독립된 수 출력
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# 인덱스별로 개수
s.value_counts()

0.00    1
1.00    1
0.50    1
0.75    1
0.25    1
dtype: int64

In [17]:
#bool 형태로 
s.isin([0.25,0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [2]:
pop_tuple = {'서울' : 97208846,
             '부산' : 3404423,
             '인천' : 2947217,
             '대구' : 2427954,
             '대전' : 1471040,
             '광주' : 1455048}

population = pd.Series(pop_tuple)
population

서울    97208846
부산     3404423
인천     2947217
대구     2427954
대전     1471040
광주     1455048
dtype: int64

In [19]:
population['서울']

97208846

### DataFrame 객체

In [21]:
pd.DataFrame([{'a':2,'b':4,'c':5}, {'a':4,'b':5,'d':7}])

a  b    c    d
0  2  4  5.0  NaN
1  4  5  NaN  7.0

In [23]:
pd.DataFrame(np.random.randn(5,5),
            columns=['a','b','c','d','e'],
            index=[1,2,3,4,5])

a         b         c         d         e
1 -1.129264  1.302646  0.633859  1.274032  1.423204
2  1.155536  0.842509  0.078143 -0.813115  0.404270
3 -1.100218 -0.606734 -1.014031  1.731697 -2.240211
4 -0.821130 -1.244295 -1.993471  1.637947 -1.268886
5 -0.092590 -0.532739 -0.638788 -0.126902  0.220212

In [3]:
male_tulpe = {'서울':4732275,
              '부산':1668618,
              '인천':1476813,
              '대구':1199815,
              '대전':734441,
              '광주':720060}

female_tulpe = {'서울':4988571,
                '부산':1736051,
                '인천':1470404,
                '대구':1229139,
                '대전':736599,
                '광주':734988}

In [4]:
korea_df = pd.DataFrame({'인구수':pop_tuple,
                        '남자인구수':male_tulpe,
                        '여자인구수':female_tulpe})
korea_df

인구수    남자인구수    여자인구수
서울  97208846  4732275  4988571
부산   3404423  1668618  1736051
인천   2947217  1476813  1470404
대구   2427954  1199815  1229139
대전   1471040   734441   736599
광주   1455048   720060   734988

In [32]:
korea_df.index

Index(['서울', '부산', '인천', '대구', '대전', '광주'], dtype='object')

In [33]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [35]:
korea_df['여자인구수']

서울    4988571
부산    1736051
인천    1470404
대구    1229139
대전     736599
광주     734988
Name: 여자인구수, dtype: int64

In [36]:
#인덱스 범위별 출력 
korea_df['서울':'인천']

인구수    남자인구수    여자인구수
서울  97208846  4732275  4988571
부산   3404423  1668618  1736051
인천   2947217  1476813  1470404

In [37]:
korea_df.iloc[0:3,:]

인구수    남자인구수    여자인구수
서울  97208846  4732275  4988571
부산   3404423  1668618  1736051
인천   2947217  1476813  1470404

### Index 객체


In [38]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [39]:
idx[1]

4

In [41]:
print(idx.size)
print(idx.shape)
print(idx.ndim) #1차원 

5
(5,)
1


#### Index 연산

In [43]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])

In [51]:
print(idx1.append(idx2)) #추가 
print(idx1.difference(idx2)) #차집합
print(idx1-idx2) #같은 순서 빼기
print(idx1.intersection(idx2)) #교집합
print(idx1 & idx2) #교집합

print(idx1.union(idx2)) #합집합
print(idx1 |idx2) #합집합
print(idx1^idx2) #여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


<ipython-input-51-43cef27a3e0b>:5: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(idx1 & idx2) #교집합
<ipython-input-51-43cef27a3e0b>:8: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(idx1 |idx2) #합집합
<ipython-input-51-43cef27a3e0b>:9: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(idx1^idx2) #여집합




---



## 인덱싱(Indexing)

In [52]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
             index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [53]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [54]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

### Series 인덱싱

In [55]:
s = pd.Series(['a','b','c','d','e'],
             index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [56]:
s.iloc[1]

'b'

In [58]:
#인덱스 재정렬
s.reindex(range(10), method='bfill') #bfill 메소드는 뒤의 값으로 결측값 채워줌

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [59]:
korea_df.남자인구수

서울    4732275
부산    1668618
인천    1476813
대구    1199815
대전     734441
광주     720060
Name: 남자인구수, dtype: int64

In [60]:
korea_df['남여비율'] = korea_df['남자인구수']*100 / korea_df['여자인구수']

In [63]:
korea_df['남여비율'] = round(korea_df['남여비율'],2)

In [64]:
korea_df

인구수    남자인구수    여자인구수    남여비율
서울  97208846  4732275  4988571   94.86
부산   3404423  1668618  1736051   96.12
인천   2947217  1476813  1470404  100.44
대구   2427954  1199815  1229139   97.61
대전   1471040   734441   736599   99.71
광주   1455048   720060   734988   97.97

In [65]:
korea_df.values[0]

array([9.7208846e+07, 4.7322750e+06, 4.9885710e+06, 9.4860000e+01])

In [66]:
korea_df.loc[:'인천',:'남자인구수']

인구수    남자인구수
서울  97208846  4732275
부산   3404423  1668618
인천   2947217  1476813

In [67]:
korea_df.loc[(korea_df.여자인구수>1000000)] #조건문 데이터프레임 형태 출력 

인구수    남자인구수    여자인구수    남여비율
서울  97208846  4732275  4988571   94.86
부산   3404423  1668618  1736051   96.12
인천   2947217  1476813  1470404  100.44
대구   2427954  1199815  1229139   97.61

In [70]:
korea_df.loc[(korea_df.여자인구수>1000000) & (korea_df.남자인구수>1000000)] #괄호 필수 

인구수    남자인구수    여자인구수    남여비율
서울  97208846  4732275  4988571   94.86
부산   3404423  1668618  1736051   96.12
인천   2947217  1476813  1470404  100.44
대구   2427954  1199815  1229139   97.61

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [5]:
idx_tuples = [('서울',2010),('서울',2020),
             ('부산',2010),('부산',2020),
             ('인천',2010),('인천',2020),
             ('대구',2010),('대구',2020),
             ('대전',2010),('대전',2020),
             ('광주',2010),('광주',2020)]
idx_tuples

[('서울', 2010),
 ('서울', 2020),
 ('부산', 2010),
 ('부산', 2020),
 ('인천', 2010),
 ('인천', 2020),
 ('대구', 2010),
 ('대구', 2020),
 ('대전', 2010),
 ('대전', 2020),
 ('광주', 2010),
 ('광주', 2020)]

In [6]:
pop_tuples = [10312545,9720846,
              2567910,3404423,
              2758296,2947217,
              2511676,2427954,
              1503664,1471040,
              1454636,1455048]

population = pd.Series(pop_tuples,index=idx_tuples)
population

(서울, 2010)    10312545
(서울, 2020)     9720846
(부산, 2010)     2567910
(부산, 2020)     3404423
(인천, 2010)     2758296
(인천, 2020)     2947217
(대구, 2010)     2511676
(대구, 2020)     2427954
(대전, 2010)     1503664
(대전, 2020)     1471040
(광주, 2010)     1454636
(광주, 2020)     1455048
dtype: int64

In [7]:
#멀티 인덱스 구성
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울', 2010),
            ('서울', 2020),
            ('부산', 2010),
            ('부산', 2020),
            ('인천', 2010),
            ('인천', 2020),
            ('대구', 2010),
            ('대구', 2020),
            ('대전', 2010),
            ('대전', 2020),
            ('광주', 2010),
            ('광주', 2020)],
           )

In [8]:
#인덱스를 멀티인덱스midx로 재구성 
population = population.reindex(midx)
population

서울  2010    10312545
    2020     9720846
부산  2010     2567910
    2020     3404423
인천  2010     2758296
    2020     2947217
대구  2010     2511676
    2020     2427954
대전  2010     1503664
    2020     1471040
광주  2010     1454636
    2020     1455048
dtype: int64

In [130]:
population.unstack() #빠르게 데이터프레임 만들기 

2010     2020
광주   1454636  1455048
대구   2511676  2427954
대전   1503664  1471040
부산   2567910  3404423
서울  10312545  9720846
인천   2758296  2947217

In [84]:
population[:,2010]

서울    10312545
부산     2567910
인천     2758296
대구     2511676
대전     1503664
광주     1454636
dtype: int64

In [133]:
population['대전',:]

2010    1503664
2020    1471040
dtype: int64

In [9]:
male_tuple = [5111259,4732275,
              1773170,1668618,
              1390356,1476813,
              1255245,1198815,
              753658,734441,
              721780,720060]

female_tuple = [5201286,49888571,
                1794740,1735805,
                1367940,1470404,
                1256431,1229139,
                750016,736599,
                732856,734988]

In [10]:
korea_mdf = pd.DataFrame({'총인구수':population,
                           '남자인구수':male_tuple,
                           '여자인구수':female_tuple})

In [11]:
korea_mdf

총인구수    남자인구수     여자인구수
서울 2010  10312545  5111259   5201286
   2020   9720846  4732275  49888571
부산 2010   2567910  1773170   1794740
   2020   3404423  1668618   1735805
인천 2010   2758296  1390356   1367940
   2020   2947217  1476813   1470404
대구 2010   2511676  1255245   1256431
   2020   2427954  1198815   1229139
대전 2010   1503664   753658    750016
   2020   1471040   734441    736599
광주 2010   1454636   721780    732856
   2020   1455048   720060    734988

In [12]:
ratio = korea_mdf['남자인구수']*100 / korea_mdf['여자인구수']
ratio

서울  2010     98.269140
    2020      9.485690
부산  2010     98.798155
    2020     96.129346
인천  2010    101.638668
    2020    100.435867
대구  2010     99.905606
    2020     97.532907
대전  2010    100.485590
    2020     99.707032
광주  2010     98.488653
    2020     97.968946
dtype: float64

In [13]:
korea_mdf = pd.DataFrame({'총인구수':population,
                           '남자인구수':male_tuple,
                           '여자인구수':female_tuple,
                           '남여비율':ratio})

In [14]:
korea_mdf

총인구수    남자인구수     여자인구수        남여비율
서울 2010  10312545  5111259   5201286   98.269140
   2020   9720846  4732275  49888571    9.485690
부산 2010   2567910  1773170   1794740   98.798155
   2020   3404423  1668618   1735805   96.129346
인천 2010   2758296  1390356   1367940  101.638668
   2020   2947217  1476813   1470404  100.435867
대구 2010   2511676  1255245   1256431   99.905606
   2020   2427954  1198815   1229139   97.532907
대전 2010   1503664   753658    750016  100.485590
   2020   1471040   734441    736599   99.707032
광주 2010   1454636   721780    732856   98.488653
   2020   1455048   720060    734988   97.968946

#### 다중 인덱스 생성

In [143]:
df = pd.DataFrame(np.random.rand(6,3),
                  index=[['a','b','c','d','e','c'],[1,2,1,2,1,2]],
                  columns=['c1','c2','c3'])
df

c1        c2        c3
a 1  0.226080  0.664388  0.702672
b 2  0.245343  0.854138  0.012768
c 1  0.756907  0.364863  0.460767
d 2  0.433313  0.627328  0.290040
e 1  0.584500  0.363870  0.726721
c 2  0.370635  0.300367  0.586904

In [144]:
pd.MultiIndex.from_arrays([['a','b','c','d','e','c'],[1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('b', 2),
            ('c', 1),
            ('d', 2),
            ('e', 1),
            ('c', 2)],
           )

In [145]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels=[['a','b','c'],[1,2]],
              codes=[[0,0,0,1,1,2],[1,2,3,1,2,3]])

In [16]:
population.index.names=['행정구역','년도']
population

행정구역  년도  
서울    2010    10312545
      2020     9720846
부산    2010     2567910
      2020     3404423
인천    2010     2758296
      2020     2947217
대구    2010     2511676
      2020     2427954
대전    2010     1503664
      2020     1471040
광주    2010     1454636
      2020     1455048
dtype: int64

#### 핵심은 멀티 인덱스 만드는법
##### 1. index에 [],[] 여러개 넣기
##### 2. pd.MultiIndex.from_tuples 사용

#### 다중 인덱스 재정렬

In [18]:
korea_mdf.index.names=['행정구역','연도'] #인덱스 이름 넣기 

In [21]:
#sort_index
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수     여자인구수        남여비율
행정구역 연도                                           
광주   2010   1454636   721780    732856   98.488653
     2020   1455048   720060    734988   97.968946
대구   2010   2511676  1255245   1256431   99.905606
     2020   2427954  1198815   1229139   97.532907
대전   2010   1503664   753658    750016  100.485590
     2020   1471040   734441    736599   99.707032
부산   2010   2567910  1773170   1794740   98.798155
     2020   3404423  1668618   1735805   96.129346
서울   2010  10312545  5111259   5201286   98.269140
     2020   9720846  4732275  49888571    9.485690
인천   2010   2758296  1390356   1367940  101.638668
     2020   2947217  1476813   1470404  100.435867

In [22]:
korea_mdf['서울':'인천']

총인구수    남자인구수     여자인구수        남여비율
행정구역 연도                                           
서울   2010  10312545  5111259   5201286   98.269140
     2020   9720846  4732275  49888571    9.485690
인천   2010   2758296  1390356   1367940  101.638668
     2020   2947217  1476813   1470404  100.435867

In [26]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                  남여비율  \
연도        2010     2020     2010     2020     2010      2020        2010   
행정구역                                                                       
광주     1454636  1455048   721780   720060   732856    734988   98.488653   
대구     2511676  2427954  1255245  1198815  1256431   1229139   99.905606   
대전     1503664  1471040   753658   734441   750016    736599  100.485590   
부산     2567910  3404423  1773170  1668618  1794740   1735805   98.798155   
서울    10312545  9720846  5111259  4732275  5201286  49888571   98.269140   
인천     2758296  2947217  1390356  1476813  1367940   1470404  101.638668   

                  
연도          2020  
행정구역              
광주     97.968946  
대구     97.532907  
대전     99.707032  
부산     96.129346  
서울      9.485690  
인천    100.435867

In [28]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수     여자인구수        남여비율
연도                                                
2010   광주   1454636   721780    732856   98.488653
2020   광주   1455048   720060    734988   97.968946
2010   대구   2511676  1255245   1256431   99.905606
2020   대구   2427954  1198815   1229139   97.532907
2010   대전   1503664   753658    750016  100.485590
2020   대전   1471040   734441    736599   99.707032
2010   부산   2567910  1773170   1794740   98.798155
2020   부산   3404423  1668618   1735805   96.129346
2010   서울  10312545  5111259   5201286   98.269140
2020   서울   9720846  4732275  49888571    9.485690
2010   인천   2758296  1390356   1367940  101.638668
2020   인천   2947217  1476813   1470404  100.435867

In [30]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

행정구역    연도      총인구수    남자인구수     여자인구수        남여비율
0    광주  2010   1454636   721780    732856   98.488653
1    광주  2020   1455048   720060    734988   97.968946
2    대구  2010   2511676  1255245   1256431   99.905606
3    대구  2020   2427954  1198815   1229139   97.532907
4    대전  2010   1503664   753658    750016  100.485590
5    대전  2020   1471040   734441    736599   99.707032
6    부산  2010   2567910  1773170   1794740   98.798155
7    부산  2020   3404423  1668618   1735805   96.129346
8    서울  2010  10312545  5111259   5201286   98.269140
9    서울  2020   9720846  4732275  49888571    9.485690
10   인천  2010   2758296  1390356   1367940  101.638668
11   인천  2020   2947217  1476813   1470404  100.435867

In [34]:
idx_flat.set_index(['행정구역','연도'])

총인구수    남자인구수     여자인구수        남여비율
행정구역 연도                                           
광주   2010   1454636   721780    732856   98.488653
     2020   1455048   720060    734988   97.968946
대구   2010   2511676  1255245   1256431   99.905606
     2020   2427954  1198815   1229139   97.532907
대전   2010   1503664   753658    750016  100.485590
     2020   1471040   734441    736599   99.707032
부산   2010   2567910  1773170   1794740   98.798155
     2020   3404423  1668618   1735805   96.129346
서울   2010  10312545  5111259   5201286   98.269140
     2020   9720846  4732275  49888571    9.485690
인천   2010   2758296  1390356   1367940  101.638668
     2020   2947217  1476813   1470404  100.435867

## 데이터 연산

In [35]:
s = pd.Series(np.random.randint(0,10,5))
s

0    2
1    5
2    9
3    6
4    1
dtype: int32

In [37]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)),
                  columns=['a','b','c'])
df

a  b  c
0  3  8  7
1  9  0  7
2  9  1  0

In [39]:
np.exp(s)

0       7.389056
1     148.413159
2    8103.083928
3     403.428793
4       2.718282
dtype: float64

In [40]:
np.cos(df*np.pi/4)

a         b         c
0 -0.707107  1.000000  0.707107
1  0.707107  1.000000  0.707107
2  0.707107  0.707107  1.000000

In [42]:
s1 = pd.Series([1,3,5,7,9],index=[0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10], index=[1,2,3,4,5])
s1+s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [43]:
s1.add(s2,fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [44]:
df1 = pd.DataFrame(np.random.randint(0,20,(3,3)),
                   columns = list('acd'))
df1

a   c   d
0  16  15   2
1   4  10   6
2   6   3  15

In [45]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),
                   columns = list('baecd'))
df2

b   a  e   c   d
0   8  12  3   1  10
1  10  17  6  17   5
2   1   3  0  14  12
3   5  17  0  13  19
4  13  17  1  16  16

In [54]:
fvalue = df1.stack().mean() #평균만들어주기 
print(df1.stack())
print(fvalue)

0  a    16
   c    15
   d     2
1  a     4
   c    10
   d     6
2  a     6
   c     3
   d    15
dtype: int32
8.555555555555555


In [50]:
df1.add(df2,fill_value=fvalue) 

a          b          c          d          e
0  28.000000  16.555556  16.000000  12.000000  11.555556
1  21.000000  18.555556  27.000000  11.000000  14.555556
2   9.000000   9.555556  17.000000  27.000000   8.555556
3  25.555556  13.555556  21.555556  27.555556   8.555556
4  25.555556  21.555556  24.555556  24.555556   9.555556

### 연산자 범용 함수


#### add()

In [55]:
a = np.random.randint(1,10,(3,3))
a

array([[6, 7, 6],
       [1, 1, 8],
       [6, 7, 1]])

In [56]:
a+a[0] 

array([[12, 14, 12],
       [ 7,  8, 14],
       [12, 14,  7]])

In [57]:
df = pd.DataFrame(a,columns=list('abc'))
df

a  b  c
0  6  7  6
1  1  1  8
2  6  7  1

In [58]:
df + df.iloc[0]

a   b   c
0  12  14  12
1   7   8  14
2  12  14   7

In [59]:
df.add(df.iloc[0])

a   b   c
0  12  14  12
1   7   8  14
2  12  14   7

#### sub() / subtract() 빼기

In [60]:
a - a[0]

array([[ 0,  0,  0],
       [-5, -6,  2],
       [ 0,  0, -5]])

In [61]:
df - df.iloc[0]

a  b  c
0  0  0  0
1 -5 -6  2
2  0  0 -5

In [62]:
df.sub(df.iloc[0])

a  b  c
0  0  0  0
1 -5 -6  2
2  0  0 -5

In [65]:
df.subtract(df['b'],axis=0) #b부분에 b를 빼줘 

a  b  c
0 -1  0 -1
1  0  0  7
2 -1  0 -6

#### mul() / multply()




In [66]:
df*df.iloc[1] #곱셈 

a  b   c
0  6  7  48
1  1  1  64
2  6  7   8

In [67]:
df.mul(df.iloc[2])

a   b  c
0  36  49  6
1   6   7  8
2  36  49  1

In [69]:
df.multiply(df.iloc[2])

a   b  c
0  36  49  6
1   6   7  8
2  36  49  1

#### truediv() /  div() / divide() / floordiv()

In [70]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.16666667, 0.14285714, 1.33333333],
       [1.        , 1.        , 0.16666667]])

In [79]:
df/df.iloc[:] #자기가 자기를 나눔 

a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [74]:
df.truediv(df.iloc[0])

a         b         c
0  1.000000  1.000000  1.000000
1  0.166667  0.142857  1.333333
2  1.000000  1.000000  0.166667

In [75]:
df.divide(df.iloc[1])

a    b      c
0  6.0  7.0  0.750
1  1.0  1.0  1.000
2  6.0  7.0  0.125

In [77]:
df.floordiv(df.iloc[:]) #나누기 두번 

a  b  c
0  1  1  1
1  1  1  1
2  1  1  1

In [78]:
a // a[0]

array([[1, 1, 1],
       [0, 0, 1],
       [1, 1, 0]])

#### mod() 나머지 연산

In [82]:
df.mod(df.iloc[0])

a  b  c
0  0  0  0
1  1  1  2
2  0  0  1

#### pow() ** -> 제곱

In [87]:
a ** a[0]

array([[ 46656, 823543,  46656],
       [     1,      1, 262144],
       [ 46656, 823543,      1]])

In [88]:
6 ** 6

46656

In [86]:
df.pow(df.iloc[0])

a       b       c
0  46656  823543   46656
1      1       1  262144
2  46656  823543       1

In [97]:
row = df.iloc[0,::2] #-> ::의 의미?
row

a    6
c    6
Name: 0, dtype: int32

In [95]:
df

a  b  c
0  6  7  6
1  1  1  8
2  6  7  1

In [91]:
df - row

a   b    c
0  0.0 NaN  0.0
1 -5.0 NaN  2.0
2  0.0 NaN -5.0

In [103]:
korea_mdf.iloc[0,:3]

총인구수     1454636.0
남자인구수     721780.0
여자인구수     732856.0
Name: (광주, 2010), dtype: float64

In [104]:
korea_mdf.iloc[0,::3]

총인구수    1.454636e+06
남여비율    9.848865e+01
Name: (광주, 2010), dtype: float64

In [99]:
korea_mdf

총인구수    남자인구수     여자인구수        남여비율
행정구역 연도                                           
광주   2010   1454636   721780    732856   98.488653
     2020   1455048   720060    734988   97.968946
대구   2010   2511676  1255245   1256431   99.905606
     2020   2427954  1198815   1229139   97.532907
대전   2010   1503664   753658    750016  100.485590
     2020   1471040   734441    736599   99.707032
부산   2010   2567910  1773170   1794740   98.798155
     2020   3404423  1668618   1735805   96.129346
서울   2010  10312545  5111259   5201286   98.269140
     2020   9720846  4732275  49888571    9.485690
인천   2010   2758296  1390356   1367940  101.638668
     2020   2947217  1476813   1470404  100.435867

### 정렬(Sort)

In [107]:
df = pd.DataFrame(np.random.randint(0,10,(4,4)),
                 columns = list('bcda'),
                 index = [2,3,4,1])
df

b  c  d  a
2  4  7  3  1
3  5  5  4  2
4  9  7  5  8
1  8  1  0  9

In [113]:
df.sort_index(axis=0) #행번호로 정렬

b  c  d  a
1  8  1  0  9
2  4  7  3  1
3  5  5  4  2
4  9  7  5  8

In [112]:
df.sort_index(axis=1) #열번호로 정렬 

a  b  c  d
2  1  4  7  3
3  2  5  5  4
4  8  9  7  5
1  9  8  1  0

In [110]:
df.sort_values(by='a')

b  c  d  a
2  4  7  3  1
3  5  5  4  2
4  9  7  5  8
1  8  1  0  9

In [111]:
df.sort_values(by=['a','b']) #a기준으로 먼저 정렬 그다음 b기준 정렬

b  c  d  a
2  4  7  3  1
3  5  5  4  2
4  9  7  5  8
1  8  1  0  9

### 순위(Ranking)


In [114]:
s = pd.Series([2,1,-1,-3,-5,-6,-1,-6,-8])
s

0    2
1    1
2   -1
3   -3
4   -5
5   -6
6   -1
7   -6
8   -8
dtype: int64

In [115]:
s.rank() #우측 숫자가 해당 인덱스의 순위 

0    9.0
1    8.0
2    6.5
3    5.0
4    4.0
5    2.5
6    6.5
7    2.5
8    1.0
dtype: float64

In [116]:
s.rank(method='first')

0    9.0
1    8.0
2    6.0
3    5.0
4    4.0
5    2.0
6    7.0
7    3.0
8    1.0
dtype: float64

In [117]:
s.rank(method='max') #1234등이 있는데 23등이 동점이면 3등으로

0    9.0
1    8.0
2    7.0
3    5.0
4    4.0
5    3.0
6    7.0
7    3.0
8    1.0
dtype: float64

In [119]:
s.rank(method='min') #1234등이 있는데 23등이 동점이면 2등으로

0    9.0
1    8.0
2    6.0
3    5.0
4    4.0
5    2.0
6    6.0
7    2.0
8    1.0
dtype: float64

### 고성능 연산

In [125]:
nrows,ncols = 100000,100

In [126]:
df1,df2,df3,df4 = (pd.DataFrame(np.random.rand(nrows,ncols)) for i in range(4))

In [129]:
%timeit df1 + df2 + df3 + df4

181 ms ± 4.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [130]:
%timeit pd.eval('df1 + df2 + df3 + df4') #pd.eval이 연산속도 빠르다! 

77.3 ms ± 2.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [131]:
df = pd.DataFrame(np.random.rand(100000, 5), columns = ['a','b','c','d','e'])
df.head()

a         b         c         d         e
0  0.191172  0.419195  0.586224  0.792652  0.058647
1  0.383232  0.091651  0.635523  0.187576  0.493385
2  0.123677  0.853613  0.972404  0.106884  0.458962
3  0.350591  0.944926  0.676202  0.590521  0.794315
4  0.357351  0.353649  0.991157  0.364863  0.637641

In [132]:
%timeit pd.eval('df.a+df.b+df.c') #데이터프레임.컬럼명 형태도 가능

3.37 ms ± 645 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [133]:
%timeit df.eval('a+b/c-d*e') #df.eval 형태로도 연산 가능!

5.16 ms ± 554 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [134]:
df.eval('f = a+b/c-d', inplace=True)
df.head()

a         b         c         d         e         f
0  0.191172  0.419195  0.586224  0.792652  0.058647  0.113596
1  0.383232  0.091651  0.635523  0.187576  0.493385  0.339870
2  0.123677  0.853613  0.972404  0.106884  0.458962  0.894631
3  0.350591  0.944926  0.676202  0.590521  0.794315  1.157472
4  0.357351  0.353649  0.991157  0.364863  0.637641  0.349293

In [135]:
col_mean = df.mean(1) #행별 평균 mean(1)
df['a'] + col_mean

0        0.551419
1        0.738438
2        0.692039
3        1.102929
4        0.866344
           ...   
99995    1.481018
99996    0.709667
99997    0.788326
99998    1.137527
99999    0.827438
Length: 100000, dtype: float64

In [138]:
df.mean()

a    0.500158
b    0.499639
c    0.500328
d    0.501753
e    0.498392
f    6.264120
dtype: float64

In [136]:
df.eval('a+@col_mean')

0        0.551419
1        0.738438
2        0.692039
3        1.102929
4        0.866344
           ...   
99995    1.481018
99996    0.709667
99997    0.788326
99998    1.137527
99999    0.827438
Length: 100000, dtype: float64

In [140]:
korea = korea_mdf.reset_index(level=(0,1))
korea.head()

행정구역    연도     총인구수    남자인구수    여자인구수        남여비율
0   광주  2010  1454636   721780   732856   98.488653
1   광주  2020  1455048   720060   734988   97.968946
2   대구  2010  2511676  1255245  1256431   99.905606
3   대구  2020  2427954  1198815  1229139   97.532907
4   대전  2010  1503664   753658   750016  100.485590

In [144]:
korea.iloc[:,1:3].mean(1)

0      728323.0
1      728534.0
2     1256843.0
3     1214987.0
4      752837.0
5      736530.0
6     1284960.0
7     1703221.5
8     5157277.5
9     4861433.0
10    1380153.0
11    1474618.5
dtype: float64

## 데이터 결합

### Concat() / Append()

In [2]:
s1 = pd.Series(['a','b'], index=[1,2])
s2 = pd.Series(['c','d'], index=[3,4])
pd.concat([s1,s2])

1    a
2    b
3    c
4    d
dtype: object

In [3]:
def create_df(cols,idx):
    data = {c:[str(c.lower()) + str(i) for i in idx] for c in cols} 
    return pd.DataFrame(data,idx)

#해석: cols를 c로 받고 idx는 i로 받아서 data는 str(c.lower())+str(i) 

In [4]:
df1 = create_df('ab',[1,2])
df1

a   b
1  a1  b1
2  a2  b2

In [11]:
df2 = create_df('ab',[3,4])
df2

a   b
3  a3  b3
4  a4  b4

In [12]:
pd.concat([df1,df2])

a   b
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [13]:
df3 = create_df('ab',[0,1])
df3

a   b
0  a0  b0
1  a1  b1

In [14]:
df4 = create_df('cd',[0,1])
df4

c   d
0  c0  d0
1  c1  d1

In [15]:
pd.concat([df3,df4])

a    b    c    d
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

#### ignore_index 옵션

In [17]:
pd.concat([df1,df3], ignore_index=True)

a   b
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

#### keys 옵션

In [18]:
pd.concat([df1,df3], keys=['X','Y'])

a   b
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [20]:
df5 = create_df('abc',[1,2])
df6 = create_df('bcd',[3,4])
pd.concat([df5,df6])

a   b   c    d
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

#### join 옵션

In [21]:
pd.concat([df5,df6], join='inner') #이너 조인 둘다 존재하는 데이터만 결합

b   c
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [22]:
df5.append(df6)

a   b   c    d
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [24]:
pd.concat([df3,df4], axis=1) #축 기준으로 

a   b   c   d
0  a0  b0  c0  d0
1  a1  b1  c1  d1

### 병합과 조인

In [25]:
df1 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],
                    '학과':['경영학과','교육학과','컴퓨터학과','통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [26]:
df2 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],
                    '입학연도':[2012,2016,2019,2020]})
df2

학생  입학연도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [27]:
df3 = pd.merge(df1,df2)
df3

학생     학과  입학연도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [28]:
df4 = pd.DataFrame({'학과':['경영학과','교육학과','컴퓨터학과','통계학과'],
                    '학과장':['황희','장영실','안창호','정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [29]:
df5 = pd.merge(df3,df4)
df5

학생     학과  입학연도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [30]:
df5 = pd.DataFrame({'학과':['경영학과','교육학과','교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                   '과목':['경영개론','기초수학','물리학','프로그래밍','운영체제','확률론']})
df5 

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [31]:
pd.merge(df1,df5) #공통된 컬럼인 학과를 기준으로 merge -> 학생이 여러개로 중복됨 

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [33]:
pd.merge(df1,df2,on='학생')

학생     학과  입학연도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [39]:
df6 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                    '성적':['A','A+','B','C']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신   C

In [40]:
pd.merge(df1,df6,left_on='학생',right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신   C

In [42]:
pd.merge(df1,df6,left_on='학생',right_on='이름').drop('이름',axis=1) #merge옵션에도 drop 옵션을 붙일 수 있다! 

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과   C

In [43]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [45]:
mdf2

입학연도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [44]:
pd.merge(mdf1,mdf2,left_index=True,right_index=True) #인덱스를 기준으로 merge 

학과  입학연도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [46]:
mdf1.join(mdf2)

학과  입학연도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [47]:
pd.merge(mdf1,df6,left_index=True,right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신   C

In [48]:
df7 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정'],
                    '주문음식':['햄버거','피자','짜장면']})
df7 

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [49]:
df8 = pd.DataFrame({'이름':['홍길동','이순신','김유신'],
                    '주문음료':['콜라','사이다','커피']})
df8 

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [50]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [51]:
pd.merge(df7, df8, how='outer') #전체 

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [52]:
pd.merge(df7, df8, how='left') #왼쪽 df에 있는것만 

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [54]:
pd.merge(df7, df8, how='right') #오른쪽 df에 있는것만 

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [56]:
df9 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                  '순위':[3,4,2,1]})
df9

이름  순위
0  홍길동   3
1  이순신   4
2  임꺽정   2
3  김유신   1

In [57]:
df10 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                  '순위':[4,3,2,1]})
df10

이름  순위
0  홍길동   4
1  이순신   3
2  임꺽정   2
3  김유신   1

In [58]:
pd.merge(df9,df10,on='이름') #on 외에 다른 같은 이름이 있으면 _x,_y로 따로 출력 

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     4     3
2  임꺽정     2     2
3  김유신     1     1

In [59]:
pd.merge(df9,df10,on='이름',suffixes=['_인기','_성적']) #suffixes 옵션

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      4      3
2  임꺽정      2      2
3  김유신      1      1

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


In [63]:
df = pd.DataFrame([[1,1.2,np.nan],
                  [2.4,5.5,4.2],
                  [np.nan,np.nan,np.nan],
                  [0.44,-3.1,-4.1]],
                  index=[1,2,3,4],
                  columns=['A','B','C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [65]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [66]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [67]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [68]:
print(df)
print(np.argmin(df),np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [71]:
print(df)

print(df.idxmin()) #컬럼별로 행별 최솟값의 위치 
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [72]:
print(df.std())
print(df.var())

A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [73]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [74]:
df['A'].skew()

1.1520696383139368

In [76]:
print(df.sum())
print(df.cumsum()) #누적합 

A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [77]:
print(df)
print(df.prod()) #곱 
print(df.cumprod()) #누적곱

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [78]:
df.diff() #차 근데 결측값있으면 계산안되고 결측값으로 뜸

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [79]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [80]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [81]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [82]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [83]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [84]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [85]:
df['A'].value_counts()

2.40    1
0.44    1
1.00    1
Name: A, dtype: int64

### GroupBy 연산

In [102]:
df = pd.DataFrame({'c1':['a','a','b','b','c','d','b'],
                  'c2':['A','B','B','A','D','C','C'],
                  'c3':np.random.randint(7),
                  'c4':np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   2  0.729825
1  a  B   2  0.413489
2  b  B   2  0.215427
3  b  A   2  0.210020
4  c  D   2  0.781124
5  d  C   2  0.169925
6  b  C   2  0.209630

In [103]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [109]:
df['c4'].groupby(df['c2']).mean() 

c2
A    0.469922
B    0.314458
C    0.189777
D    0.781124
Name: c4, dtype: float64

In [110]:
df['c4'].groupby(df['c2']).std()  #c2를 그룹바이하고 c4값의 std를 알려줘 

c2
A    0.367558
B    0.140051
C    0.028076
D         NaN
Name: c4, dtype: float64

In [111]:
df['c4'].groupby([df['c1'],df['c2']]).mean() 

c1  c2
a   A     0.729825
    B     0.413489
b   A     0.210020
    B     0.215427
    C     0.209630
c   D     0.781124
d   C     0.169925
Name: c4, dtype: float64

In [112]:
df.groupby('c1').mean()

c3        c4
c1              
a    2  0.571657
b    2  0.211692
c    2  0.781124
d    2  0.169925

In [113]:
df.groupby(['c1','c2']).mean()

c3        c4
c1 c2              
a  A    2  0.729825
   B    2  0.413489
b  A    2  0.210020
   B    2  0.215427
   C    2  0.209630
c  D    2  0.781124
d  C    2  0.169925

In [114]:
df.groupby(['c1','c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [115]:
for c1,group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   2  0.729825
1  a  B   2  0.413489
b
  c1 c2  c3        c4
2  b  B   2  0.215427
3  b  A   2  0.210020
6  b  C   2  0.209630
c
  c1 c2  c3        c4
4  c  D   2  0.781124
d
  c1 c2  c3        c4
5  d  C   2  0.169925


In [116]:
for [c1,c2],group in df.groupby(['c1','c2']):
    print((c1,c2))
    print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   2  0.729825
('a', 'B')
  c1 c2  c3        c4
1  a  B   2  0.413489
('b', 'A')
  c1 c2  c3       c4
3  b  A   2  0.21002
('b', 'B')
  c1 c2  c3        c4
2  b  B   2  0.215427
('b', 'C')
  c1 c2  c3       c4
6  b  C   2  0.20963
('c', 'D')
  c1 c2  c3        c4
4  c  D   2  0.781124
('d', 'C')
  c1 c2  c3        c4
5  d  C   2  0.169925


In [117]:
df.groupby(['c1','c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.729825
   B   0.413489
b  A   0.210020
   B   0.215427
   C   0.209630
c  D   0.781124
d  C   0.169925

In [118]:
df.groupby('c1')['c3'].quantile()

c1
a    2.0
b    2.0
c    2.0
d    2.0
Name: c3, dtype: float64

In [119]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [121]:
df.groupby('c1')['c4'].median()

c1
a    0.571657
b    0.210020
c    0.781124
d    0.169925
Name: c4, dtype: float64

In [122]:
df.groupby(['c1','c2'])['c4'].agg(['mean','min','max'])

mean       min       max
c1 c2                              
a  A   0.729825  0.729825  0.729825
   B   0.413489  0.413489  0.413489
b  A   0.210020  0.210020  0.210020
   B   0.215427  0.215427  0.215427
   C   0.209630  0.209630  0.209630
c  D   0.781124  0.781124  0.781124
d  C   0.169925  0.169925  0.169925

In [124]:
df.groupby(['c1','c2'],as_index=False)['c4'].mean() #인덱스를 제거 

c1 c2        c4
0  a  A  0.729825
1  a  B  0.413489
2  b  A  0.210020
3  b  B  0.215427
4  b  C  0.209630
5  c  D  0.781124
6  d  C  0.169925

In [125]:
df.groupby(['c1','c2'],group_keys=False)['c4'].mean() #인덱스를 제거 

c1  c2
a   A     0.729825
    B     0.413489
b   A     0.210020
    B     0.215427
    C     0.209630
c   D     0.781124
d   C     0.169925
Name: c4, dtype: float64

In [130]:
df

c1 c2  c3        c4
0  a  A   2  0.729825
1  a  B   2  0.413489
2  b  B   2  0.215427
3  b  A   2  0.210020
4  c  D   2  0.781124
5  d  C   2  0.169925
6  b  C   2  0.209630

In [142]:
def top(df,n=7,columns='c1'):
    return df.sort_values(by=columns)[:n]
top(df)

c1 c2  c3        c4
0  a  A   2  0.729825
1  a  B   2  0.413489
2  b  B   2  0.215427
3  b  A   2  0.210020
6  b  C   2  0.209630
4  c  D   2  0.781124
5  d  C   2  0.169925

In [149]:
df.groupby('c1',).apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   2  0.729825
   1  a  B   2  0.413489
b  2  b  B   2  0.215427
   3  b  A   2  0.210020
   6  b  C   2  0.209630
c  4  c  D   2  0.781124
d  5  d  C   2  0.169925

In [150]:
#만약 위 프레임에서 c1을 없애고 싶다면
df.groupby('c1',).apply(top).drop('c1',axis=1)

c2  c3        c4
c1                   
a  0  A   2  0.729825
   1  B   2  0.413489
b  2  B   2  0.215427
   3  A   2  0.210020
   6  C   2  0.209630
c  4  D   2  0.781124
d  5  C   2  0.169925

### 피벗 테이블(Pivot Table)


In [151]:
df.pivot_table(['c1','c4'],
               index=['c1'],
               columns=['c2'])

c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   2.0  2.0  NaN  NaN  0.729825  0.413489       NaN       NaN
b   2.0  2.0  2.0  NaN  0.210020  0.215427  0.209630       NaN
c   NaN  NaN  NaN  2.0       NaN       NaN       NaN  0.781124
d   NaN  NaN  2.0  NaN       NaN       NaN  0.169925       NaN

In [156]:
df.pivot_table(['c1','c4'],
               index=['c1'],
               columns=['c2'],
               fill_value=0)

c3                 c4                              
c2  A  B  C  D         A         B         C         D
c1                                                    
a   2  2  0  0  0.729825  0.413489  0.000000  0.000000
b   2  2  2  0  0.210020  0.215427  0.209630  0.000000
c   0  0  0  2  0.000000  0.000000  0.000000  0.781124
d   0  0  2  0  0.000000  0.000000  0.169925  0.000000

In [157]:
pd.crosstab(df.c1,df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [158]:
pd.crosstab(df.c1,df.c2, values=df.c3,aggfunc=sum,margins=True)

c2     A    B    C    D  All
c1                          
a    2.0  2.0  NaN  NaN    4
b    2.0  2.0  2.0  NaN    6
c    NaN  NaN  NaN  2.0    2
d    NaN  NaN  2.0  NaN    2
All  4.0  4.0  4.0  2.0   14

### 범주형(Categorical) 데이터


In [160]:
s = pd.Series(['c1','c2']*5)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c2
6    c1
7    c2
8    c1
9    c2
dtype: object

In [161]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [162]:
pd.value_counts(s)

c1    5
c2    5
dtype: int64

In [163]:
code = pd.Series([0,1,0,1,0]*2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [164]:
d = pd.Series(['c1','c2'])
d

0    c1
1    c2
dtype: object

In [165]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [167]:
df = pd.DataFrame({'id':np.arange(len(s)),
                   'c':s,
                   'v':np.random.randint(1000,5000,size=len(s))})
df

id   c     v
0   0  c1  1334
1   1  c2  4343
2   2  c1  1362
3   3  c2  4443
4   4  c1  1586
5   5  c2  1005
6   6  c1  3613
7   7  c2  3997
8   8  c1  4572
9   9  c2  3627

In [169]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c2
6    c1
7    c2
8    c1
9    c2
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [170]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c2', 'c1', 'c2', 'c1', 'c2']
Categories (2, object): ['c1', 'c2']

In [171]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [172]:
c.values.codes

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int8)

In [173]:
df['c']=c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c2
6    c1
7    c2
8    c1
9    c2
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

## 문자열 연산

#### 문자열 연산자

In [179]:
name_tuple = ['Suzy','Karina','Kazuha','Iu','Yna','Zlatan','Rooney','Messi',None]
name_tuple

['Suzy', 'Karina', 'Kazuha', 'Iu', 'Yna', 'Zlatan', 'Rooney', 'Messi', None]

In [181]:
names = pd.Series(name_tuple)

In [182]:
names.str.lower()

0      suzy
1    karina
2    kazuha
3        iu
4       yna
5    zlatan
6    rooney
7     messi
8      None
dtype: object

In [183]:
names.str.split()

0      [Suzy]
1    [Karina]
2    [Kazuha]
3        [Iu]
4       [Yna]
5    [Zlatan]
6    [Rooney]
7     [Messi]
8        None
dtype: object

#### 정규표현식


In [184]:
names.str.match('[A-Za-z]+')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    None
dtype: object

In [185]:
names.str.findall('[A-Za-z]+')

0      [Suzy]
1    [Karina]
2    [Kazuha]
3        [Iu]
4       [Yna]
5    [Zlatan]
6    [Rooney]
7     [Messi]
8        None
dtype: object

## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly